version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
install:
- ps: >-
    $env:CommitHash = "$env:APPVEYOR_REPO_COMMIT"

cache: '%USERPROFILE%\.nuget\packages'
build_script:
- ps: >
    dotnet --version

    $PackArguments = '-o', '..\buildoutput', '--no-build'
    
    If ($env:APPVEYOR_REPO_BRANCH -ne "master") 
    {
        $PackArguments = $PackArguments + '--version-suffix', '"-$env:APPVEYOR_BUILD_NUMBER"'
    }
    
    dotnet build -v q

    dotnet pack .\src\TokenBinding\TokenBinding.csproj $PackArguments
    
    dotnet pack .\src\MicrosoftGraphBinding\MicrosoftGraphBinding.csproj $PackArguments

test_script:
- ps: >-
    dotnet test .\test\TokenExtension.Tests\ -v q --no-build
    
    dotnet test .\test\MicrosoftGraph.Tests\ -v q --no-build

artifacts:
- path: buildoutput\*.nupkg
  name: Binaries
hosts:
  api.nuget.org: 93.184.221.200